name: deploy-tencent

on:
  push:
    branches: ['main']

jobs:
  dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo codebase ðŸš€
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Nodejs setup ðŸš€
        uses: actions/setup-node@v1
  deploy:
    runs-on: ubuntu-latest
    needs: [dependency]
    steps:
      - name: Checkout repo codebase ðŸš€
        uses: actions/checkout@v4
      - name: Deploy to AWS ðŸ’¹ + ðŸš€
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Kitakursus..."
            cd /var/www/project/kitakursus-landing
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            npm run build
            free && sync && echo 3 > /proc/sys/vm/drop_caches && free
